### ISSUE TITLE
Cookie not working

### ISSUE THREAD

**Issue by deltabravozulu** [wabarc/archive.is#21]
```
$ export ARCHIVE_COOKIE=cf_clearance=747c8285c60f3297fb1d52e89228f043a56af6bf-1652837033-TKBSOLBK
$ archive.is https://www.google.com
[2022-05-17T15:40:47] [ERROR] exec: "tor": executable file not found in $PATH
https://www.google.com => archive.today is unavailable.
```

**Comment by waybackarchiver** [comment]
@deltabravozulu Thank you for your report.

I tried to run `archive.is` with `ARCHIVE_COOKIE` and it is still working. However, the cookie item `cf_clearance` has an expiration date. Please try again with the updated cookie.

**Comment by Strubbl** [comment]
I can reproduce the issue even with a valid cookie. It is valid until tomorrow.

```
$ ARCHIVE_COOKIE=632f6a59d01234123545142064404a6f4677-1653149389-ASDFTGH /home/strubbl/go/bin/archive.is http://google.com
[2022-05-21T18:52:51] [ERROR] exec: "tor": executable file not found in $PATH
http://google.com => archive.today is unavailable.

```

**Comment by Strubbl** [comment]
I changed the scheme to https in line https://github.com/wabarc/archive.is/blob/main/is.go#L40= and it works now.

**Comment by waybackarchiver** [comment]
@Strubbl Thank you for testing. The host scheme has been changed at [10b3531](https://github.com/wabarc/archive.is/commit/10b3531f17052517dfdb0854eb02928f924bf662)
